--------------------------------------------------------
--  File created - Saturday-September-22-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAHASISWA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MAHASISWA" 
   (	"NIM" NUMBER(*,0), 
	"NAMA" VARCHAR2(100 BYTE), 
	"TGL_LAHIR" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MAHASISWA
SET DEFINE OFF;
Insert into SYSTEM.MAHASISWA (NIM,NAMA,TGL_LAHIR) values (1,'Atik',to_date('01-JAN-95','DD-MON-RR'));
Insert into SYSTEM.MAHASISWA (NIM,NAMA,TGL_LAHIR) values (2,'Dina',to_date('19-JUL-95','DD-MON-RR'));
Insert into SYSTEM.MAHASISWA (NIM,NAMA,TGL_LAHIR) values (3,'Sutay',to_date('26-JUL-95','DD-MON-RR'));
Insert into SYSTEM.MAHASISWA (NIM,NAMA,TGL_LAHIR) values (4,'Piscok',to_date('01-JUL-95','DD-MON-RR'));
Insert into SYSTEM.MAHASISWA (NIM,NAMA,TGL_LAHIR) values (5,'Raisol',to_date('30-APR-95','DD-MON-RR'));
Insert into SYSTEM.MAHASISWA (NIM,NAMA,TGL_LAHIR) values (10027,'Murti',to_date('25-DEC-94','DD-MON-RR'));
Insert into SYSTEM.MAHASISWA (NIM,NAMA,TGL_LAHIR) values (10209,'Risti',to_date('31-DEC-94','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SYS_C006989
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C006989" ON "SYSTEM"."MAHASISWA" ("NIM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MAHASISWA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MAHASISWA" ADD PRIMARY KEY ("NIM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."MAHASISWA" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MAHASISWA" MODIFY ("NIM" NOT NULL ENABLE);
